In [3]:
import pandas as pd

In [5]:
#207 AARP Survey
df_2017 = pd.read_csv('Data/2017 AARP/aarp_2017.csv')

C:\Users\Tonyj\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (4,142,143,144,145) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [6]:
df_2017

,Unnamed: 0,case#,market,community,e_lans,age_samp,phone_type,qs1,qs2,qs3,...,q15m,new_qd5,new_qd6,new_qd10,weight,charleston,surv_lang,othq10,shorewood,County_code
0,0,1.0,"Albany County, NY","Albany County, New York",NaN,Age 50 plus,Cell,NaN,NaN,Yes,...,Poor,No,Somewhat likely,NaN,1.082259,NaN,NaN,NaN,NaN,Albany
1,1,2.0,"Albany County, NY","Albany County, New York",NaN,Age 50 plus,Cell,NaN,NaN,Yes,...,[DO NOT READ] This feature does not exist in y...,No,Not very likely,NaN,0.589884,NaN,NaN,NaN,NaN,Albany
2,2,3.0,"Albany County, NY","Albany County, New York",NaN,Age 50 plus,Cell,NaN,NaN,Yes,...,Poor,No,Extremely likely,NaN,0.775785,NaN,NaN,NaN,NaN,Albany
3,3,4.0,"Albany County, NY","Albany County, New York",NaN,Age 50 plus,Cell,NaN,NaN,Yes,...,[DO NOT READ] This feature does not exist in y...,No,Not very likely,NaN,0.775785,NaN,NaN,NaN,NaN,Albany
4,4,6.0,"Albany County, NY","Albany County, New York",NaN,Age 50 plus,Landline,Person on the phone is youngest male age 45+_50+,NaN,Yes,...,Fair,No,Not very likely,NaN,0.502886,NaN,NaN,NaN,NaN,Albany
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6665,6665,11690.0,"Milwaukee County, WI","Milwaukee County, Wisconsin",NaN,Age 45 plus,Cell,NaN,NaN,Yes,...,Poor,No,Very likely,NaN,0.278159,NaN,NaN,NaN,Outside Village of Shorewood,Milwaukee
6666,6666,11736.0,"Milwaukee County, WI","Milwaukee County, Wisconsin",NaN,Age 45 plus,Cell,NaN,NaN,Yes,...,Fair,No,Not very likely,NaN,0.423463,NaN,NaN,NaN,Inside Village of Shorewood,Milwaukee
6667,6667,11743.0,"Milwaukee County, WI","Milwaukee County, Wisconsin",NaN,Age 45 plus,Cell,NaN,NaN,Yes,...,Good,No,Not very likely,NaN,0.370765,NaN,NaN,NaN,Outside Village of Shorewood,Milwaukee
6668,6668,11772.0,"Milwaukee County, WI","Milwaukee County, Wisconsin",NaN,Age 45 plus,Landline,Person on the phone is youngest male age 45+_50+,NaN,Yes,...,[DO NOT READ] This feature does not exist in y...,No,Not very likely,NaN,0.522951,NaN,NaN,NaN,Outside Village of Shorewood,Milwaukee
6669,6669,11773.0,"Milwaukee County, WI","Milwaukee County, Wisconsin",NaN,Age 45 plus,Landline,Person on the phone is youngest male age 45+_50+,NaN,Yes,...,Excellent,No,Somewhat likely,NaN,1.234919,NaN,NaN,NaN,Inside Village of Shorewood,Milwaukee